name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16, 18, 20, 21, 21.6]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8.15.4
    - uses: actions/setup-node@v4
      # name: Setup node | ${{ matrix.node-version }}
      name: Setup node 21.6
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: 21.6
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run prisma:generate
    - run: pnpm run test
    - name: Generate Tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ github.repository }}:${{ steps.generate_tag.outputs.sha }},${{ github.repository }}:latest

    # - name: Build docker image
    #   run: docker build -t $GITHUB_REPOSITORY:${{ steps.generate_tag.outputs.sha }} .

    # - name: Push docker image
    #   run: docker push $GITHUB_REPOSITORY:${{ steps.generate_tag.outputs.sha }}
